<?php
/**
 * Instala Matomo por CLI: tablas, superusuario, sitio y GeoIP a nivel ciudad.
 * El finalize no arranca el kernel de Matomo: con installation_in_progress el
 * plugin Installation imprime el wizard HTML y aborta.
 */
if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "cli only\n");
    exit(1);
}

$root = '/var/www/html';
$configFile = $root . '/config/config.ini.php';
$phase = $argv[1] ?? 'all';

$host = getenv('MATOMO_DATABASE_HOST') ?: getenv('MATOMO_DB_HOST') ?: 'matomo-db';
$dbUser = getenv('MATOMO_DATABASE_USERNAME') ?: getenv('MATOMO_DB_USER') ?: 'matomo';
$dbPass = getenv('MATOMO_DATABASE_PASSWORD') ?: getenv('MATOMO_DB_PASSWORD') ?: '';
$dbName = getenv('MATOMO_DATABASE_DBNAME') ?: getenv('MATOMO_DB_NAME') ?: 'matomo';
$prefix = getenv('MATOMO_DATABASE_TABLES_PREFIX') ?: 'matomo_';
$login = getenv('MATOMO_USER') ?: 'admin';
$password = getenv('MATOMO_PASSWORD') ?: '';
$email = getenv('MATOMO_EMAIL') ?: 'admin@localhost.local';
$siteName = getenv('MATOMO_SITE_NAME') ?: 'PropMap';
$siteUrl = getenv('MATOMO_SITE_URL') ?: 'http://127.0.0.1:8000';
$tz = getenv('MATOMO_TIMEZONE') ?: 'America/Argentina/Buenos_Aires';

if ($password === '' || strlen($password) < 12) {
    fwrite(STDERR, "[matomo-install] MATOMO_PASSWORD vacio o menor a 12 caracteres\n");
    exit(1);
}

function ini_escape(string $value): string
{
    return str_replace(['\\', '"'], ['\\\\', '\\"'], $value);
}

function pdo_db(string $host, string $dbUser, string $dbPass, string $dbName): PDO
{
    $pdo = new PDO("mysql:host={$host};dbname={$dbName};charset=utf8mb4", $dbUser, $dbPass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);
    return $pdo;
}

function table_count(PDO $pdo): int
{
    return (int) $pdo->query('SHOW TABLES')->rowCount();
}

function write_config(
    string $file,
    string $host,
    string $dbUser,
    string $dbPass,
    string $dbName,
    string $prefix,
    string $tz
): void {
    $salt = bin2hex(random_bytes(32));
    $dbPassEsc = ini_escape($dbPass);
    $body = <<<INI
; <?php exit; ?> DO NOT REMOVE THIS LINE
; file generated by PropMap
[database]
host = "{$host}"
username = "{$dbUser}"
password = "{$dbPassEsc}"
dbname = "{$dbName}"
tables_prefix = "{$prefix}"
adapter = "PDO\\MYSQL"
type = "InnoDB"
schema = "Mysql"
charset = "utf8mb4"

[General]
salt = "{$salt}"
installation_in_progress = 1
trusted_hosts[] = "127.0.0.1:3102"
trusted_hosts[] = "localhost:3102"
trusted_hosts[] = "127.0.0.1"
trusted_hosts[] = "localhost"
trusted_hosts[] = "matomo"
force_ssl = 0
enable_trusted_host_check = 1
assume_secure_protocol = 0
proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"
proxy_host_headers[] = "HTTP_X_FORWARDED_HOST"
proxy_client_headers[] = "HTTP_X_REAL_IP"
proxy_ip_read_last_in_list = 1
proxy_ips[] = "10.0.0.0/8"
proxy_ips[] = "172.16.0.0/12"
proxy_ips[] = "192.168.0.0/16"
proxy_ips[] = "127.0.0.1/32"
noreply_email_address = "noreply@localhost.local"
emails_enabled = 0
enable_update_communication = 0
default_timezone = "{$tz}"
default_currency = "ARS"

[Tracker]
ignore_visits_from_localhost = 0

INI;
    if (file_put_contents($file, $body) === false) {
        fwrite(STDERR, "[matomo-install] no pude escribir config.ini.php\n");
        exit(1);
    }
    @chmod($file, 0660);
}

function boot(string $root): void
{
    if (!defined('PIWIK_DOCUMENT_ROOT')) {
        define('PIWIK_DOCUMENT_ROOT', $root);
    }
    if (!defined('PIWIK_INCLUDE_PATH')) {
        define('PIWIK_INCLUDE_PATH', $root);
    }
    if (!defined('PIWIK_USER_PATH')) {
        define('PIWIK_USER_PATH', $root);
    }
    if (!defined('PIWIK_ENABLE_ERROR_HANDLER')) {
        define('PIWIK_ENABLE_ERROR_HANDLER', false);
    }
    if (!defined('PIWIK_ENABLE_DISPATCH')) {
        define('PIWIK_ENABLE_DISPATCH', false);
    }
    require_once $root . '/core/bootstrap.php';
    \Piwik\FrontController::setUpSafeMode();
    $environment = new \Piwik\Application\Environment('cli');
    $environment->init();
}

function mark_installed(string $file): void
{
    if (!is_file($file)) {
        return;
    }
    $raw = (string) file_get_contents($file);
    $raw = preg_replace('/^installation_in_progress\s*=\s*1\s*$/m', '', $raw) ?? $raw;
    $raw = preg_replace('/^installation_first_accessed\s*=\s*.*$/m', '', $raw) ?? $raw;
    file_put_contents($file, $raw);
    ensure_trusted_hosts($file);
}

function ensure_trusted_hosts(string $file): void
{
    if (!is_file($file)) {
        return;
    }
    $raw = (string) file_get_contents($file);
    $needed = ['127.0.0.1:3102', 'localhost:3102', '127.0.0.1', 'localhost', 'matomo'];
    foreach ([getenv('APP_PUBLIC_URL') ?: '', getenv('MATOMO_PUBLIC_URL') ?: ''] as $url) {
        $host = parse_url((string) $url, PHP_URL_HOST);
        if (is_string($host) && $host !== '' && !in_array($host, $needed, true)) {
            $needed[] = $host;
        }
    }
    $missing = [];
    foreach ($needed as $host) {
        if (!str_contains($raw, 'trusted_hosts[] = "' . $host . '"')) {
            $missing[] = $host;
        }
    }
    if ($missing) {
        $block = '';
        foreach ($missing as $host) {
            $block .= 'trusted_hosts[] = "' . $host . '"' . "\n";
        }
        if (preg_match('/^trusted_hosts\[\] = /m', $raw)) {
            $raw = preg_replace('/^(trusted_hosts\[\] = .*)$/m', $block . '$1', $raw, 1) ?? $raw;
        } elseif (str_contains($raw, '[General]')) {
            $raw = str_replace('[General]', "[General]\n" . rtrim($block), $raw);
        } else {
            $raw .= "\n[General]\n" . $block;
        }
    }
    $public = (string) (getenv('APP_PUBLIC_URL') ?: getenv('MATOMO_PUBLIC_URL') ?: '');
    if (str_starts_with($public, 'https://') && !preg_match('/^assume_secure_protocol\s*=\s*1\s*$/m', $raw)) {
        if (preg_match('/^assume_secure_protocol\s*=/m', $raw)) {
            $raw = preg_replace('/^assume_secure_protocol\s*=\s*.*$/m', 'assume_secure_protocol = 1', $raw) ?? $raw;
        } elseif (str_contains($raw, '[General]')) {
            $raw = str_replace('[General]', "[General]\nassume_secure_protocol = 1", $raw);
        }
    }
    if (!str_contains($raw, 'proxy_host_headers[]')) {
        if (str_contains($raw, '[General]')) {
            $raw = str_replace('[General]', "[General]\nproxy_host_headers[] = \"HTTP_X_FORWARDED_HOST\"", $raw);
        }
    }
    if (!preg_match('/^proxy_ip_read_last_in_list\s*=/m', $raw)) {
        if (str_contains($raw, '[General]')) {
            $raw = str_replace('[General]', "[General]\nproxy_ip_read_last_in_list = 1", $raw);
        }
    } else {
        $raw = preg_replace('/^proxy_ip_read_last_in_list\s*=\s*.*$/m', 'proxy_ip_read_last_in_list = 1', $raw) ?? $raw;
    }
    $proxyIps = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', '127.0.0.1/32'];
    $missingProxy = [];
    foreach ($proxyIps as $cidr) {
        if (!str_contains($raw, 'proxy_ips[] = "' . $cidr . '"')) {
            $missingProxy[] = $cidr;
        }
    }
    if ($missingProxy) {
        $block = '';
        foreach ($missingProxy as $cidr) {
            $block .= 'proxy_ips[] = "' . $cidr . '"' . "\n";
        }
        if (preg_match('/^proxy_ips\[\] = /m', $raw)) {
            $raw = preg_replace('/^(proxy_ips\[\] = .*)$/m', $block . '$1', $raw, 1) ?? $raw;
        } elseif (str_contains($raw, '[General]')) {
            $raw = str_replace('[General]', "[General]\n" . rtrim($block), $raw);
        }
    }
    file_put_contents($file, $raw);
}

function upsert_option(PDO $pdo, string $name, string $value): void
{
    $stmt = $pdo->prepare(
        'INSERT INTO matomo_option (option_name, option_value, autoload) VALUES (?, ?, 1)
         ON DUPLICATE KEY UPDATE option_value = VALUES(option_value)'
    );
    $stmt->execute([$name, $value]);
}

if ($phase === 'config' || $phase === 'all') {
    $raw = is_file($configFile) ? (string) file_get_contents($configFile) : '';
    if (!str_contains($raw, '[database]') || !str_contains($raw, 'salt =')) {
        echo "[matomo-install] escribiendo config.ini.php\n";
        write_config($configFile, $host, $dbUser, $dbPass, $dbName, $prefix, $tz);
    }
}

if ($phase === 'tables' || $phase === 'all') {
    $pdo = pdo_db($host, $dbUser, $dbPass, $dbName);
    if (table_count($pdo) < 8) {
        echo "[matomo-install] creando tablas\n";
        boot($root);
        if (!\Piwik\DbHelper::isInstalled()) {
            \Piwik\DbHelper::createTables();
            \Piwik\DbHelper::createAnonymousUser();
            \Piwik\DbHelper::recordInstallVersion();
            \Piwik\Updater::recordComponentSuccessfullyUpdated('core', \Piwik\Version::VERSION);
        }
    } else {
        echo "[matomo-install] tablas ya existen\n";
    }
    if ($phase === 'tables') {
        exit(0);
    }
}

if ($phase === 'all') {
    passthru('php ' . escapeshellarg($root . '/console') . ' core:update --yes', $updateCode);
    if ($updateCode !== 0) {
        fwrite(STDERR, "[matomo-install] core:update fallo ($updateCode)\n");
    }
}

if ($phase === 'finalize' || $phase === 'all') {
    $pdo = pdo_db($host, $dbUser, $dbPass, $dbName);
    $hash = password_hash($password, PASSWORD_BCRYPT);

    $exists = $pdo->prepare('SELECT login, superuser_access FROM matomo_user WHERE login = ?');
    $exists->execute([$login]);
    $user = $exists->fetch(PDO::FETCH_ASSOC);
    if (!$user) {
        echo "[matomo-install] creando superusuario\n";
        $ins = $pdo->prepare(
            'INSERT INTO matomo_user (login, password, email, twofactor_secret, superuser_access, date_registered, ts_password_modified)
             VALUES (?, ?, ?, "", 1, NOW(), NOW())'
        );
        $ins->execute([$login, $hash, $email]);
    } elseif ((int) $user['superuser_access'] !== 1) {
        echo "[matomo-install] promoviendo superusuario\n";
        $pdo->prepare('UPDATE matomo_user SET superuser_access = 1 WHERE login = ?')->execute([$login]);
    }

    $siteId = (string) $pdo->query('SELECT idsite FROM matomo_site ORDER BY idsite ASC LIMIT 1')->fetchColumn();
    if ($siteId === '' || $siteId === false) {
        echo "[matomo-install] creando sitio\n";
        $insSite = $pdo->prepare(
            'INSERT INTO matomo_site
                (name, description, main_url, ts_created, ecommerce, sitesearch,
                 sitesearch_keyword_parameters, sitesearch_category_parameters,
                 timezone, currency, exclude_unknown_urls, excluded_ips,
                 excluded_parameters, excluded_user_agents, excluded_referrers,
                 `group`, type, keep_url_fragment, creator_login)
             VALUES (?, "", ?, NOW(), 0, 1, "", "", ?, "ARS", 0, "", "", "", "", "", "website", 0, ?)'
        );
        $insSite->execute([$siteName, $siteUrl, $tz, $login]);
        $siteId = (string) $pdo->lastInsertId();
        $urlStmt = $pdo->prepare('INSERT IGNORE INTO matomo_site_url (idsite, url) VALUES (?, ?)');
        $urlStmt->execute([$siteId, $siteUrl]);
        if ($siteUrl !== 'http://localhost:8000') {
            $urlStmt->execute([$siteId, 'http://localhost:8000']);
        }
    }
    $publicApp = rtrim((string) (getenv('APP_PUBLIC_URL') ?: ''), '/');
    if ($siteId && $publicApp !== '') {
        $alias = $pdo->prepare('INSERT IGNORE INTO matomo_site_url (idsite, url) VALUES (?, ?)');
        $alias->execute([$siteId, $publicApp]);
    }

    upsert_option($pdo, 'usercountry.location_provider', 'geoip2php');
    upsert_option($pdo, 'PrivacyManager.ipAnonymizerEnabled', '0');
    upsert_option($pdo, 'PrivacyManager.useAnonymizedIpForVisitEnrichment', '0');
    upsert_option($pdo, 'PrivacyManager.ipAddressMaskLength', '0');

    mark_installed($configFile);
    echo "[matomo-install] SITE_ID={$siteId}\n";
    echo "[matomo-install] listo\n";
    exit(0);
}

exit(0);
